
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// NOTE: use process.env.DATABASE_URL directly rather than Prisma's strict
// env() helper. env() throws at config-load time if the var is missing, which
// breaks `prisma generate` during the install/build phase on hosts (e.g.
// Hostinger) that have no DATABASE_URL set yet. process.env returns undefined
// instead of throwing, so `generate` succeeds with no DB var, while commands
// that actually connect (migrate deploy) still resolve the real value when it
// is present at deploy time.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Empty-string fallback keeps the type as `string` and avoids throwing at
    // config-load time; `generate` ignores it and commands that connect get
    // the real value from process.env when it is set.
    url: process.env.DATABASE_URL ?? "",
  },
});
