import type { FacilitiesPageConfig } from '../types';

export const fasilitasPageConfig: FacilitiesPageConfig = {
  pageHeader: {
    breadcrumb: [
      { label: 'Beranda', href: '/' },
      { label: 'Fasilitas & Kegiatan' },
    ],
    title: 'Fasilitas & Kegiatan',
    subtitle: 'Sarana lengkap dan kegiatan beragam untuk mendukung proses belajar mengajar',
  },
  sarana: {
    meta: {
      eyebrow: 'SARANA',
      title: 'Fasilitas Sekolah',
      subtitle: 'Lingkungan belajar yang nyaman, lengkap, dan kondusif untuk menunjang prestasi siswa',
    },
    statStrip: [
      { value: '12', label: 'Ruang Kelas' },
      { value: '2', label: 'Laboratorium' },
      { value: '1', label: 'Perpustakaan' },
      { value: '1', label: 'Lapangan Olahraga' },
    ],
    featured: [
      { id: 'f1', name: 'Perpustakaan', description: 'Koleksi buku lengkap dan ruang baca nyaman', emoji: '📚', gradientFrom: '#1565C0', gradientTo: '#1E88E5', span: 'wide' },
      { id: 'f2', name: 'Laboratorium IPA', description: 'Peralatan sains lengkap', emoji: '🔬', gradientFrom: '#16A34A', gradientTo: '#22C55E' },
      { id: 'f3', name: 'Laboratorium Komputer', description: 'PC modern & internet', emoji: '💻', gradientFrom: '#F59E0B', gradientTo: '#FBBF24' },
      { id: 'f4', name: 'Lapangan Olahraga', description: 'Lapangan serbaguna & trek lari', emoji: '🏟', gradientFrom: '#0D47A1', gradientTo: '#1565C0', span: 'wide' },
      { id: 'f5', name: 'Mushola Al-Hidayah', description: 'Ibadah & kegiatan keagamaan', emoji: '🕌', gradientFrom: '#7C3AED', gradientTo: '#A855F7' },
      { id: 'f6', name: '12 Ruang Kelas', description: 'Ber-AC & multimedia', emoji: '🏫', gradientFrom: '#0F766E', gradientTo: '#14B8A6' },
    ],
    mini: [
      { id: 'm1', icon: '🏥', name: 'UKS' },
      { id: 'm2', icon: '🍽️', name: 'Kantin Sehat' },
      { id: 'm3', icon: '🏛️', name: 'Ruang OSIS' },
      { id: 'm4', icon: '👩‍💼', name: 'Ruang Guru' },
      { id: 'm5', icon: '🏢', name: 'Ruang TU' },
      { id: 'm6', icon: '🚻', name: 'Toilet Bersih' },
      { id: 'm7', icon: '🅿️', name: 'Parkir Luas' },
      { id: 'm8', icon: '🌿', name: 'Taman Sekolah' },
      { id: 'm9', icon: '📡', name: 'WiFi Sekolah' },
      { id: 'm10', icon: '🎤', name: 'Aula Serbaguna' },
    ],
  },
  ekskul: {
    meta: {
      eyebrow: 'EKSTRAKURIKULER',
      title: 'Kembangkan Minat & Bakatmu',
      subtitle: 'Beragam pilihan kegiatan untuk pengembangan diri siswa di luar jam pelajaran',
    },
    statStrip: [
      { value: '15+', label: 'Ekstrakurikuler' },
      { value: '5', label: 'Kategori' },
      { value: '30+', label: 'Pembina Berpengalaman' },
    ],
    filterLabels: {
      all: 'Semua',
      wajib: 'Wajib',
      olahraga: 'Olahraga',
      seni: 'Seni',
      akademik: 'Akademik',
      keagamaan: 'Keagamaan',
      lainnya: 'Lainnya',
    },
    items: [
      { id: 'e1', name: 'Pramuka', category: 'wajib', description: 'Pembentukan karakter & kepemimpinan', pembina: 'Kak Hendra, S.Pd.', schedule: 'Jumat, 14.00–16.00', icon: '⛺' },
      { id: 'e2', name: 'Futsal', category: 'olahraga', description: 'Tim futsal berprestasi di tingkat kabupaten', pembina: 'Pak Usman, S.Pd.', schedule: 'Selasa & Kamis', achievement: '5 Prestasi', icon: '⚽' },
      { id: 'e3', name: 'Bola Voli', category: 'olahraga', description: 'Voli putra dan putri yang kompetitif', pembina: 'Pak Irwan, S.Pd.', schedule: 'Senin & Rabu', icon: '🏐' },
      { id: 'e4', name: 'Bulu Tangkis', category: 'olahraga', description: 'Teknik dasar hingga kompetisi', pembina: 'Pak Dani', schedule: 'Sabtu pagi', achievement: '3 Prestasi', icon: '🏸' },
      { id: 'e5', name: 'Pencak Silat', category: 'olahraga', description: 'Seni bela diri tradisional Indonesia', pembina: 'Pak Yusuf', schedule: 'Rabu, 14.00–16.00', icon: '🥋' },
      { id: 'e6', name: 'Marawis', category: 'seni', description: 'Musik islami yang khas dan membanggakan', pembina: 'Pak Ridwan', schedule: 'Kamis, 14.00–16.00', achievement: '2 Prestasi', icon: '🪘' },
      { id: 'e7', name: 'Tari Tradisional', category: 'seni', description: 'Pelestarian budaya & tari daerah Banten', pembina: 'Bu Sari, S.Sn.', schedule: 'Selasa, 14.00–16.00', icon: '💃' },
      { id: 'e8', name: 'Paduan Suara', category: 'seni', description: 'Olah vokal & harmoni tim juara', pembina: 'Bu Dewi', schedule: 'Rabu & Jumat', achievement: 'Juara 1 Kabupaten', icon: '🎤' },
      { id: 'e9', name: 'KIR', category: 'akademik', description: 'Karya Ilmiah Remaja yang inovatif', pembina: 'Bu Nurul, S.Pd.', schedule: 'Senin, 14.00–16.00', achievement: 'Juara 1 Kabupaten', icon: '🔬' },
      { id: 'e10', name: 'English Club', category: 'akademik', description: 'Percakapan & debat bahasa Inggris', pembina: 'Bu Dewi, S.Pd.', schedule: 'Kamis, 14.00–15.30', icon: '🌐' },
      { id: 'e11', name: 'Rohis', category: 'keagamaan', description: 'Rohani Islam & kegiatan keislaman', pembina: 'Bu Lilis, S.Pd.I.', schedule: 'Jumat siang', icon: '🕌' },
      { id: 'e12', name: "Tahfidz Al-Qur'an", category: 'keagamaan', description: "Menghafal Al-Qur'an dengan metode mudah", pembina: 'Ust. Fauzi', schedule: 'Senin & Rabu pagi', icon: '📖' },
      { id: 'e13', name: 'PMR', category: 'lainnya', description: 'Palang Merah Remaja & pertolongan pertama', pembina: 'Bu Marlina', schedule: 'Sabtu, 08.00–10.00', icon: '⛑️' },
      { id: 'e14', name: 'Paskibra', category: 'lainnya', description: 'Pasukan pengibar bendera kebanggaan sekolah', pembina: 'Pak Bambang', schedule: 'Sabtu, 07.00–09.00', icon: '🚩' },
      { id: 'e15', name: 'Jurnalistik', category: 'lainnya', description: 'Tulis berita, blog, & majalah dinding sekolah', pembina: 'Pak Ahmad, M.Pd.', schedule: 'Kamis, 14.00–15.30', icon: '📰' },
      { id: 'e16', name: 'OSIS', category: 'lainnya', description: 'Organisasi Siswa Intra Sekolah', pembina: 'Kesiswaan', schedule: 'Senin, 13.30–15.00', icon: '🏛️' },
    ],
  },
  kegiatan: {
    meta: {
      eyebrow: 'KEGIATAN RUTIN',
      title: 'Kegiatan Rutin Sekolah',
      subtitle: 'Aktivitas yang membentuk karakter, kebersamaan, dan kedisiplinan siswa',
    },
    cards: [
      { id: 'r1', icon: '🚩', title: 'Upacara Bendera', frequency: 'Setiap Senin', description: 'Upacara pengibaran bendera merah putih untuk menumbuhkan jiwa nasionalisme dan patriotisme.' },
      { id: 'r2', icon: '🧹', title: 'Jumat Bersih/Sehat', frequency: 'Setiap Jumat', description: 'Kegiatan kebersihan lingkungan sekolah bersama dan senam kesehatan untuk menjaga kebugaran.' },
      { id: 'r3', icon: '🕌', title: 'Shalat Dzuhur Berjamaah', frequency: 'Setiap Hari', description: 'Shalat berjamaah bersama seluruh warga sekolah sebagai pembiasaan ibadah dan ukhuwah islamiyah.' },
      { id: 'r4', icon: '📖', title: 'Literasi Pagi', frequency: '15 Menit Setiap Hari', description: 'Membaca buku selama 15 menit sebelum pelajaran dimulai untuk menumbuhkan budaya literasi.' },
      { id: 'r5', icon: '🏆', title: 'Class Meeting', frequency: 'Akhir Semester', description: 'Kompetisi antar kelas dalam berbagai bidang untuk mempererat persahabatan dan semangat sportivitas.' },
      { id: 'r6', icon: '🇮🇩', title: 'Hari Besar Nasional', frequency: 'Sesuai Kalender', description: 'Peringatan hari kemerdekaan, hari pahlawan, dan hari besar nasional lainnya dengan berbagai kegiatan.' },
      { id: 'r7', icon: '☪️', title: 'Hari Besar Keagamaan', frequency: 'Sesuai Kalender', description: "Peringatan Maulid Nabi, Isra Mi'raj, dan hari besar keagamaan lainnya dengan kegiatan yang bermakna." },
      { id: 'r8', icon: '🎓', title: 'MPLS', frequency: 'Awal Tahun Ajaran', description: 'Masa Pengenalan Lingkungan Sekolah bagi siswa baru kelas 7 agar dapat beradaptasi dengan nyaman.' },
    ],
  },
  galeri: {
    meta: {
      eyebrow: 'GALERI',
      title: 'Momen di SMPN 3 Kresek',
      subtitle: 'Dokumentasi kegiatan dan kebersamaan keluarga besar sekolah kami',
    },
    filterLabels: {
      all: 'Semua',
      akademik: 'Akademik',
      ekskul: 'Ekstrakurikuler',
      acara: 'Acara',
      fasilitas: 'Fasilitas',
    },
    items: [
      { id: 'fg1', caption: 'Kegiatan Belajar Mengajar Kelas 8', emoji: '📚', gradientFrom: '#1565C0', gradientTo: '#1E88E5', category: 'akademik', span: 'tall' },
      { id: 'fg2', caption: 'Upacara HUT RI ke-79', emoji: '🇮🇩', gradientFrom: '#FEE2E2', gradientTo: '#FCA5A5', category: 'acara', span: 'wide' },
      { id: 'fg3', caption: 'Latihan Futsal', emoji: '⚽', gradientFrom: '#D1FAE5', gradientTo: '#6EE7B7', category: 'ekskul' },
      { id: 'fg4', caption: 'Laboratorium Komputer', emoji: '💻', gradientFrom: '#DBEAFE', gradientTo: '#93C5FD', category: 'fasilitas' },
      { id: 'fg5', caption: 'Pentas Seni Akhir Tahun', emoji: '🎭', gradientFrom: '#F3E8FF', gradientTo: '#C4B5FD', category: 'acara' },
      { id: 'fg6', caption: 'Paskibra — HUT RI', emoji: '🚩', gradientFrom: '#FEF9C3', gradientTo: '#FDE68A', category: 'ekskul', span: 'tall' },
      { id: 'fg7', caption: 'Praktikum IPA Kelas 7', emoji: '🔬', gradientFrom: '#ECFDF5', gradientTo: '#6EE7B7', category: 'akademik' },
      { id: 'fg8', caption: 'Taman & Area Hijau Sekolah', emoji: '🌿', gradientFrom: '#F0FDF4', gradientTo: '#86EFAC', category: 'fasilitas' },
      { id: 'fg9', caption: 'Wisuda & Pelepasan Kelas 9', emoji: '🎓', gradientFrom: '#FFF7ED', gradientTo: '#FED7AA', category: 'acara', span: 'wide' },
      { id: 'fg10', caption: 'Penampilan Tari Tradisional', emoji: '💃', gradientFrom: '#FDF4FF', gradientTo: '#E879F9', category: 'ekskul' },
    ],
  },
  tatib: {
    meta: {
      eyebrow: 'TATA TERTIB',
      title: 'Tata Tertib & Aturan Sekolah',
      subtitle: 'Pedoman bersama untuk menciptakan lingkungan belajar yang kondusif dan nyaman',
    },
    accordions: [
      {
        id: 'tt1',
        icon: '📋',
        title: 'Kewajiban Siswa',
        items: [
          'Hadir di sekolah sebelum pukul 07.00 WIB',
          'Berpakaian seragam sesuai ketentuan yang berlaku',
          'Mengikuti upacara bendera setiap Senin pagi',
          'Menghormati guru, staf, dan sesama siswa',
          'Mengikuti semua kegiatan pembelajaran dengan aktif',
          'Menjaga kebersihan dan ketertiban lingkungan sekolah',
          'Mengikuti kegiatan ekstrakurikuler wajib (Pramuka)',
          'Meminta izin kepada guru/wali kelas jika tidak hadir',
        ],
      },
      {
        id: 'tt2',
        icon: '🚫',
        title: 'Larangan',
        items: [
          'Membawa dan menggunakan handphone selama KBM berlangsung',
          'Membawa senjata tajam atau benda berbahaya',
          'Berkelahi atau melakukan kekerasan fisik maupun verbal',
          'Membawa, mengonsumsi, atau mengedarkan narkoba',
          'Merokok di lingkungan sekolah',
          'Melakukan tindakan bullying dalam bentuk apapun',
          'Merusak fasilitas dan sarana sekolah',
          'Keluar dari lingkungan sekolah tanpa izin',
        ],
      },
      {
        id: 'tt3',
        icon: '👔',
        title: 'Seragam Sekolah',
        items: [
          'Senin & Selasa: Seragam putih-biru lengkap dengan atribut',
          'Rabu & Kamis: Seragam batik sekolah',
          'Jumat: Seragam muslim/pramuka',
          'Sepatu warna hitam, kaos kaki putih (Senin-Kamis)',
          'Rambut rapi, tidak dicat; tidak memakai aksesori berlebihan',
          'Baju dimasukkan ke dalam celana/rok',
        ],
      },
      {
        id: 'tt4',
        icon: '📱',
        title: 'Penggunaan Gadget',
        items: [
          'HP dinonaktifkan atau di-silent selama kegiatan belajar',
          'HP hanya boleh digunakan pada jam istirahat',
          'Penggunaan HP untuk tujuan pembelajaran seizin guru',
          'Konten yang tidak sesuai usia dilarang keras',
          'HP yang disita karena pelanggaran dikembalikan kepada orang tua',
        ],
      },
      {
        id: 'tt5',
        icon: '📅',
        title: 'Kehadiran & Kedisiplinan',
        items: [
          'Absensi minimum 75% untuk dapat mengikuti penilaian akhir semester',
          'Izin sakit harus disertai surat keterangan dokter atau orang tua',
          'Keterlambatan lebih dari 15 menit dicatat sebagai alpha',
          'Izin meninggalkan pelajaran harus melalui guru BK atau wali kelas',
          'Absensi berlebihan akan berdampak pada penilaian dan kenaikan kelas',
        ],
      },
      {
        id: 'tt6',
        icon: '⚖️',
        title: 'Sanksi & Konsekuensi',
        items: [
          'Ringan: Teguran lisan dan pencatatan di buku catatan siswa',
          'Sedang: Pemanggilan orang tua dan surat peringatan',
          'Berat: Skorsing dan pembinaan intensif bersama orang tua',
          'Sangat berat: Dikembalikan kepada orang tua (dikeluarkan)',
          'Semua pelanggaran dicatat dalam sistem poin siswa',
        ],
      },
      {
        id: 'tt7',
        icon: '🌿',
        title: 'Kebersihan & Lingkungan',
        items: [
          'Setiap kelas bertanggung jawab atas kebersihan ruang kelasnya',
          'Piket harian dilaksanakan sesuai jadwal yang telah ditetapkan',
          'Sampah dibuang pada tempat yang telah disediakan',
          'Menjaga tanaman dan fasilitas taman sekolah',
          'Mengikuti program Jumat Bersih secara aktif',
        ],
      },
    ],
    // Phase 3: download sourced from DocumentSlot 'tata-tertib' at assembler
    // runtime via getDocumentSlotWithMedia. Static value stays null.
    documentSlot: null,
  },
  ctaFinal: {
    title: 'Tertarik Bergabung dengan Kami?',
    subtitle: 'Hubungi sekolah untuk informasi penerimaan siswa baru atau jadwalkan kunjungan ke SMPN 3 Kresek.',
    primary: { label: 'Hubungi Kami Sekarang', href: '/kontak' },
    secondary: { label: 'Pelajari Profil Sekolah', href: '/profil' },
  },
};
