-- Phase 4: per-entity photo crop region (normalized 0–1 fractions).
-- All nullable; existing rows stay uncropped (center-fill) until edited.

ALTER TABLE "Teacher"          ADD COLUMN "photoCropX" DOUBLE PRECISION, ADD COLUMN "photoCropY" DOUBLE PRECISION, ADD COLUMN "photoCropW" DOUBLE PRECISION, ADD COLUMN "photoCropH" DOUBLE PRECISION;
ALTER TABLE "Achievement"      ADD COLUMN "photoCropX" DOUBLE PRECISION, ADD COLUMN "photoCropY" DOUBLE PRECISION, ADD COLUMN "photoCropW" DOUBLE PRECISION, ADD COLUMN "photoCropH" DOUBLE PRECISION;
ALTER TABLE "Extracurricular"  ADD COLUMN "photoCropX" DOUBLE PRECISION, ADD COLUMN "photoCropY" DOUBLE PRECISION, ADD COLUMN "photoCropW" DOUBLE PRECISION, ADD COLUMN "photoCropH" DOUBLE PRECISION;
ALTER TABLE "GalleryItem"      ADD COLUMN "photoCropX" DOUBLE PRECISION, ADD COLUMN "photoCropY" DOUBLE PRECISION, ADD COLUMN "photoCropW" DOUBLE PRECISION, ADD COLUMN "photoCropH" DOUBLE PRECISION;
ALTER TABLE "Facility"         ADD COLUMN "photoCropX" DOUBLE PRECISION, ADD COLUMN "photoCropY" DOUBLE PRECISION, ADD COLUMN "photoCropW" DOUBLE PRECISION, ADD COLUMN "photoCropH" DOUBLE PRECISION;
